<?php

namespace Database\Seeders;

Use App\Models\Desa;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DesaSeeder extends Seeder
{
    public function run(): void
    {
        $desaData = [
            //Jatipuro
            ['nama_desa' => 'NGEPUNGSARI', 'id_puskesmas' => 1],
            ['nama_desa' => 'JATIPURWO', 'id_puskesmas' => 1],
            ['nama_desa' => 'JATIPURO', 'id_puskesmas' => 1],
            ['nama_desa' => 'JATISOBO', 'id_puskesmas' => 1],
            ['nama_desa' => 'JATIWARNO', 'id_puskesmas' => 1],
            ['nama_desa' => 'JATIMULYO', 'id_puskesmas' => 1],
            ['nama_desa' => 'JATISUKO', 'id_puskesmas' => 1],
            ['nama_desa' => 'JATIHARJO', 'id_puskesmas' => 1],
            ['nama_desa' => 'JATIKUWUNG', 'id_puskesmas' => 1],
            ['nama_desa' => 'JATIROYO', 'id_puskesmas' => 1],
            //Jatiyoso
            ['nama_desa' => 'JATISAWIT', 'id_puskesmas' => 2],
            ['nama_desa' => 'PETUNG', 'id_puskesmas' => 2],
            ['nama_desa' => 'WONOKELING', 'id_puskesmas' => 2],
            ['nama_desa' => 'JATIYOSO', 'id_puskesmas' => 2],
            ['nama_desa' => 'TLOBO', 'id_puskesmas' => 2],
            ['nama_desa' => 'WONOREJO', 'id_puskesmas' => 2],
            ['nama_desa' => 'BERUK', 'id_puskesmas' => 2],
            ['nama_desa' => 'KARANGSARI', 'id_puskesmas' => 2],
            ['nama_desa' => 'WUKIRSAWIT', 'id_puskesmas' => 2],
            //Jumapolo
            ['nama_desa' => 'PASEBAN', 'id_puskesmas' => 3],
            ['nama_desa' => 'LEMAHBANG', 'id_puskesmas' => 3],
            ['nama_desa' => 'KARANGBANGUN', 'id_puskesmas' => 3],
            ['nama_desa' => 'PLOSO', 'id_puskesmas' => 3],
            ['nama_desa' => 'GIRIWONDO', 'id_puskesmas' => 3],
            ['nama_desa' => 'KADIPIRO', 'id_puskesmas' => 3],
            ['nama_desa' => 'JUMANTORO', 'id_puskesmas' => 3],
            ['nama_desa' => 'KEDAWUNG', 'id_puskesmas' => 3],
            ['nama_desa' => 'BAKALAN', 'id_puskesmas' => 3],
            ['nama_desa' => 'JUMAPOLO', 'id_puskesmas' => 3],
            ['nama_desa' => 'KWANGSAN', 'id_puskesmas' => 3],
            ['nama_desa' => 'JATIREJO', 'id_puskesmas' => 3],
            //Jumantono
            ['nama_desa' => 'SEDAYU', 'id_puskesmas' => 4],
            ['nama_desa' => 'KEBAK', 'id_puskesmas' => 4],
            ['nama_desa' => 'GEMANTAR', 'id_puskesmas' => 4],
            ['nama_desa' => 'TUNGGULREJO', 'id_puskesmas' => 4],
            ['nama_desa' => 'GENENGAN', 'id_puskesmas' => 4],
            ['nama_desa' => 'NGUNUT', 'id_puskesmas' => 4],
            ['nama_desa' => 'TUGU', 'id_puskesmas' => 4],
            ['nama_desa' => 'SUKOSARI', 'id_puskesmas' => 4],
            ['nama_desa' => 'SAMBIREJO', 'id_puskesmas' => 4],
            ['nama_desa' => 'BLORONG', 'id_puskesmas' => 4],
            ['nama_desa' => 'SRINGIN', 'id_puskesmas' => 4],
            //Matesih
            ['nama_desa' => 'NGADILUWIH', 'id_puskesmas' => 5],
            ['nama_desa' => 'DAWUNG', 'id_puskesmas' => 5],
            ['nama_desa' => 'MATESIH', 'id_puskesmas' => 5],
            ['nama_desa' => 'KARANGBANGUN', 'id_puskesmas' => 5],
            ['nama_desa' => 'KORIPAN', 'id_puskesmas' => 5],
            ['nama_desa' => 'GIRILAYU', 'id_puskesmas' => 5],
            ['nama_desa' => 'PABLENGAN', 'id_puskesmas' => 5],
            ['nama_desa' => 'PLOSOREJO', 'id_puskesmas' => 5],
            ['nama_desa' => 'GANTIWARNO ', 'id_puskesmas' => 5],
            //Tawangmangu
            ['nama_desa' => 'BANDARDAWUNG', 'id_puskesmas' => 6],
            ['nama_desa' => 'SEPANJANG', 'id_puskesmas' => 6],
            ['nama_desa' => 'TAWANGMANGU', 'id_puskesmas' => 6],
            ['nama_desa' => 'KALISORO', 'id_puskesmas' => 6],
            ['nama_desa' => 'BLUMBANG', 'id_puskesmas' => 6],
            ['nama_desa' => 'GONDOSULI', 'id_puskesmas' => 6],
            ['nama_desa' => 'TENGKLIK', 'id_puskesmas' => 6],
            ['nama_desa' => 'NGLEBAK', 'id_puskesmas' => 6],
            ['nama_desa' => 'KARANGLO', 'id_puskesmas' => 6],
            ['nama_desa' => 'PLUMBON', 'id_puskesmas' => 6],
            //Ngargoyoso
            ['nama_desa' => 'PUNTUKREJO', 'id_puskesmas' => 7],
            ['nama_desa' => 'BERJO', 'id_puskesmas' => 7],
            ['nama_desa' => 'GIRIMULYO', 'id_puskesmas' => 7],
            ['nama_desa' => 'SEGOROGUNUNG', 'id_puskesmas' => 7],
            ['nama_desa' => 'KEMUNING', 'id_puskesmas' => 7],
            ['nama_desa' => 'NGLEGOK', 'id_puskesmas' => 7],
            ['nama_desa' => 'DUKUH', 'id_puskesmas' => 7],
            ['nama_desa' => 'JATIREJO', 'id_puskesmas' => 7],
            ['nama_desa' => 'NGARGOYOSO', 'id_puskesmas' => 7],
            //Karangpandan
            ['nama_desa' => 'BANGSRI', 'id_puskesmas' => 8],
            ['nama_desa' => 'NGEMPLAK', 'id_puskesmas' => 8],
            ['nama_desa' => 'DOPLANG', 'id_puskesmas' => 8],
            ['nama_desa' => 'GERDU', 'id_puskesmas' => 8],
            ['nama_desa' => 'KARANG', 'id_puskesmas' => 8],
            ['nama_desa' => 'SALAM', 'id_puskesmas' => 8],
            ['nama_desa' => 'KARANGPANDAN', 'id_puskesmas' => 8],
            ['nama_desa' => 'TOHKUNING', 'id_puskesmas' => 8],
            ['nama_desa' => 'GONDANGMANIS', 'id_puskesmas' => 8],
            ['nama_desa' => 'DAYU', 'id_puskesmas' => 8],
            ['nama_desa' => 'HARJOSARI', 'id_puskesmas' => 8],
            //Karanganyar
            ['nama_desa' => 'LALUNG', 'id_puskesmas' => 9],
            ['nama_desa' => 'BOLONG', 'id_puskesmas' => 9],
            ['nama_desa' => 'JATIHARJO', 'id_puskesmas' => 9],
            ['nama_desa' => 'TEGALGEDE', 'id_puskesmas' => 9],
            ['nama_desa' => 'JUNGKE', 'id_puskesmas' => 9],
            ['nama_desa' => 'CANGAKAN', 'id_puskesmas' => 9],
            ['nama_desa' => 'KARANGANYAR', 'id_puskesmas' => 9],
            ['nama_desa' => 'BEJEN', 'id_puskesmas' => 9],
            ['nama_desa' => 'POPONGAN', 'id_puskesmas' => 9],
            ['nama_desa' => 'GAYAMDOMPO', 'id_puskesmas' => 9],
            ['nama_desa' => 'DELINGAN', 'id_puskesmas' => 9],
            ['nama_desa' => 'GEDONG', 'id_puskesmas' => 9],
            //Tasikmadu
            ['nama_desa' => 'BURAN', 'id_puskesmas' => 10],
            ['nama_desa' => 'PAPAHAN', 'id_puskesmas' => 10],
            ['nama_desa' => 'NGIJO', 'id_puskesmas' => 10],
            ['nama_desa' => 'GAUM', 'id_puskesmas' => 10],
            ['nama_desa' => 'SURUH', 'id_puskesmas' => 10],
            ['nama_desa' => 'PANDEYAN', 'id_puskesmas' => 10],
            ['nama_desa' => 'KARANGMOJO', 'id_puskesmas' => 10],
            ['nama_desa' => 'KALING', 'id_puskesmas' => 10],
            ['nama_desa' => 'WONOLOPO', 'id_puskesmas' => 10],
            ['nama_desa' => 'KALIJIRAK', 'id_puskesmas' => 10],
            //Jaten I
            ['nama_desa' => 'SURUH KALANG', 'id_puskesmas' => 11],
            ['nama_desa' => 'JATI', 'id_puskesmas' => 11],
            ['nama_desa' => 'JATEN', 'id_puskesmas' => 11],
            ['nama_desa' => 'JETIS', 'id_puskesmas' => 11],
            ['nama_desa' => 'BRUJUL', 'id_puskesmas' => 11],
            //Jaten II
            ['nama_desa' => 'DAGEN', 'id_puskesmas' => 12],
            ['nama_desa' => 'NGRINGO', 'id_puskesmas' => 12],
            ['nama_desa' => 'SROYO', 'id_puskesmas' => 12],
            //Colomadu I
            ['nama_desa' => 'NGASEM', 'id_puskesmas' => 13],
            ['nama_desa' => 'BOLON', 'id_puskesmas' => 13],
            ['nama_desa' => 'MALANGJIWAN', 'id_puskesmas' => 13],
            ['nama_desa' => 'PAULAN', 'id_puskesmas' => 13],
            ['nama_desa' => 'GAJAHAN', 'id_puskesmas' => 13],
            ['nama_desa' => 'GAWANAN', 'id_puskesmas' => 13],
            //Colomadu II
            ['nama_desa' => 'BLULUKAN', 'id_puskesmas' => 14],
            ['nama_desa' => 'GEDONGAN', 'id_puskesmas' => 14],
            ['nama_desa' => 'TOHUDAN', 'id_puskesmas' => 14],
            ['nama_desa' => 'BATURAN', 'id_puskesmas' => 14],
            ['nama_desa' => 'KLODRAN', 'id_puskesmas' => 14],
            //Gondangrejo
            ['nama_desa' => 'WONOREJO', 'id_puskesmas' => 15],
            ['nama_desa' => 'PLESUNGAN', 'id_puskesmas' => 15],
            ['nama_desa' => 'JATIKUWUNG', 'id_puskesmas' => 15],
            ['nama_desa' => 'SELOKATON', 'id_puskesmas' => 15],
            ['nama_desa' => 'BULUREJO', 'id_puskesmas' => 15],
            ['nama_desa' => 'REJOSARI', 'id_puskesmas' => 15],
            ['nama_desa' => 'JERUKSAWIT', 'id_puskesmas' => 15],
            ['nama_desa' => 'KARANGTURI', 'id_puskesmas' => 15],
            ['nama_desa' => 'KRAGAN', 'id_puskesmas' => 15],
            ['nama_desa' => 'WONOSARI', 'id_puskesmas' => 15],
            ['nama_desa' => 'DAYU', 'id_puskesmas' => 15],
            ['nama_desa' => 'TUBAN', 'id_puskesmas' => 15],
            ['nama_desa' => 'KRENDOWAHONO', 'id_puskesmas' => 15],
            //Kebakkramat I
            ['nama_desa' => 'KEMIRI', 'id_puskesmas' => 16],
            ['nama_desa' => 'NANGSRI', 'id_puskesmas' => 16],
            ['nama_desa' => 'MACANAN', 'id_puskesmas' => 16],
            ['nama_desa' => 'KEBAK', 'id_puskesmas' => 16],
            ['nama_desa' => 'WARU', 'id_puskesmas' => 16],
            //Kebakkramat II
            ['nama_desa' => 'ALASTUWO', 'id_puskesmas' => 17],
            ['nama_desa' => 'BANJARHARJO', 'id_puskesmas' => 17],
            ['nama_desa' => 'MALANGGATEN', 'id_puskesmas' => 17],
            ['nama_desa' => 'KALIWULUH', 'id_puskesmas' => 17],
            ['nama_desa' => 'PULOSARI', 'id_puskesmas' => 17],
            //Mojogedang I
            ['nama_desa' => 'SEWUREJO', 'id_puskesmas' => 18],
            ['nama_desa' => 'NGADIREJO', 'id_puskesmas' => 18],
            ['nama_desa' => 'MOJOGEDANG', 'id_puskesmas' => 18],
            ['nama_desa' => 'POJOK', 'id_puskesmas' => 18],
            ['nama_desa' => 'MOJOROTO', 'id_puskesmas' => 18],
            ['nama_desa' => 'KALIBOTO', 'id_puskesmas' => 18],
            ['nama_desa' => 'PENDEM', 'id_puskesmas' => 18],
            //Mojogedang II
            ['nama_desa' => 'BUNTAR', 'id_puskesmas' => 19],
            ['nama_desa' => 'GEBYOG', 'id_puskesmas' => 19],
            ['nama_desa' => 'GENTUNGAN', 'id_puskesmas' => 19],
            ['nama_desa' => 'PERENG', 'id_puskesmas' => 19],
            ['nama_desa' => 'MUNGGUR', 'id_puskesmas' => 19],
            ['nama_desa' => 'KEDUNGJERUK', 'id_puskesmas' => 19],
            //Kerjo
            ['nama_desa' => 'KUTO', 'id_puskesmas' => 20],
            ['nama_desa' => 'TAMANSARI', 'id_puskesmas' => 20],
            ['nama_desa' => 'GANTEN', 'id_puskesmas' => 20],
            ['nama_desa' => 'GEMPOLAN', 'id_puskesmas' => 20],
            ['nama_desa' => 'PLOSOREJO', 'id_puskesmas' => 20],
            ['nama_desa' => 'KARANGREJO', 'id_puskesmas' => 20],
            ['nama_desa' => 'KWADUNGAN', 'id_puskesmas' => 20],
            ['nama_desa' => 'BOTOK', 'id_puskesmas' => 20],
            ['nama_desa' => 'SUMBEREJO', 'id_puskesmas' => 20],
            ['nama_desa' => 'TAWANGSARI', 'id_puskesmas' => 20],
            //Jenawi
            ['nama_desa' => 'GUMENG', 'id_puskesmas' => 21],
            ['nama_desa' => 'ANGGRASMANIS', 'id_puskesmas' => 21],
            ['nama_desa' => 'JENAWI', 'id_puskesmas' => 21],
            ['nama_desa' => 'TRENGGULI', 'id_puskesmas' => 21],
            ['nama_desa' => 'SIDOMUKTI', 'id_puskesmas' => 21],
            ['nama_desa' => 'BALONG', 'id_puskesmas' => 21],
            ['nama_desa' => 'SELOROMO', 'id_puskesmas' => 21],
            ['nama_desa' => 'MENJING', 'id_puskesmas' => 21],
            ['nama_desa' => 'LEMPONG', 'id_puskesmas' => 21],
        ];

        Desa::insert($desaData);
    }
}
